### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by Til-g-pock** [WeiiswurstDev/AdminTools3#3]
Hi, I'm pretty new to this and would like to know how I can apply commands for different modules.
Like /v for Vanish

**Comment by ArvedEh** [comment]
You should be able to do /v right now, if it doesnt work for you, I can mark this as a bugreport and try it out on my own testserver.

**Comment by Til-g-pock** [comment]
yeah it doesn't work.

**Comment by ArvedEh** [comment]
Alright, lemme check if its reproducable on my local machine

**Comment by Til-g-pock** [comment]
btw I'm on paper-1.16.5-437
and other aliases like /wb work

**Comment by ArvedEh** [comment]
Alright, just checked ingame and indeed, the default config doesnt include the /v alias
This can be fixed though: Add this into your config.yml in the AdminTools3 folder:
```
module:
  [...] (here should be a bunch of stuff already)
  vanish:
    aliases:
     - v
```
This should work, but in case it doesnt, please let me know!
If you need any further help, I'm also available on the [Discord Server](https://discord.gg/YDkQbE7) which is where most of the support requests arrive. You can also get notifications for plugin updates there :)

**Comment by Til-g-pock** [comment]
ok, I added it. do I have to restart the server or is there a reload command?

**Comment by ArvedEh** [comment]
There is no reload config command (yet) - restarting the server should work though.

**Comment by Til-g-pock** [comment]
ok, great plugin :)
